apiVersion: apps/v1
kind: Deployment
metadata:
  name: alma-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: target
      image: alma
  template:
    metadata:
      labels:
        app: target
        image: alma
    spec:
      containers:
        - name: almalinux
          image: almalinux:8.5
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
