apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-deployment
  labels:
    app: target
spec:
  replicas: 2
  selector:
    matchLabels:
      app: target
      image: centos
  template:
    metadata:
      labels:
        app: target
        image: centos
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"
      containers:
        - name: centos
          image: centos:latest
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
